// Generated types - do not edit manually
// This file is automatically generated by the build script

import { EncryptedLabelGroup } from 'runar-ts-serializer/src/encryption.js';
import { type RunarEncryptable } from './index.js';
import { TestProfile } from '../test_fixtures/dist/test_fixtures/test_fixtures';

export interface EncryptedTestProfile extends RunarEncryptable<TestProfile, EncryptedTestProfile> {
  id: string;
  system_encrypted: EncryptedLabelGroup;
  user_encrypted: EncryptedLabelGroup;
  search_encrypted: EncryptedLabelGroup;
  system_only_encrypted: EncryptedLabelGroup;
}
