// Generated types - do not edit manually
// This file is automatically generated by the build script

import { EncryptedLabelGroup } from 'runar-ts-serializer/src/encryption.js';

export interface EncryptedTestProfile {
  id: string;
  system_encrypted: EncryptedLabelGroup;
  user_encrypted: EncryptedLabelGroup;
  search_encrypted: EncryptedLabelGroup;
  system_only_encrypted: EncryptedLabelGroup;
}
